//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BetterFarmAnimalVariety.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5927/11343/32/448/32/16/White Cow,Brown Cow")]
        public string FarmAnimals_Cows {
            get {
                return ((string)(this["FarmAnimals_Cows"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5922/11334/0/448/32/16/White Chicken,Brown Chicken,Blue Chicken,Void Chicken")]
        public string FarmAnimals_Chickens {
            get {
                return ((string)(this["FarmAnimals_Chickens"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5942/11352/32/464/32/16/Sheep")]
        public string FarmAnimals_Sheep {
            get {
                return ((string)(this["FarmAnimals_Sheep"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5933/11349/64/448/32/16/Goat")]
        public string FarmAnimals_Goats {
            get {
                return ((string)(this["FarmAnimals_Goats"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5948/11346/0/480/32/16/Pig")]
        public string FarmAnimals_Pigs {
            get {
                return ((string)(this["FarmAnimals_Pigs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5937/11337/0/464/32/16/Duck")]
        public string FarmAnimals_Ducks {
            get {
                return ((string)(this["FarmAnimals_Ducks"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5945/11340/64/464/32/16/Rabbit")]
        public string FarmAnimals_Rabbits {
            get {
                return ((string)(this["FarmAnimals_Rabbits"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("-1/-1/-1/-1/-1/-1/Dinosaur")]
        public string FarmAnimals_Dinosaurs {
            get {
                return ((string)(this["FarmAnimals_Dinosaurs"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("assets")]
        public string AssetsDirectory {
            get {
                return ((string)(this["AssetsDirectory"]));
            }
        }
    }
}
